### ISSUE TITLE
error processing documents

### ISSUE THREAD

**Issue by JosedeKruif** [jlonij/frame-generator-gui#1]
Prototype of GUI does not work on local machine. Tried two local machines using 24 kb file (txt file) because limit is set to 25 kb. Did not succeed in generating any result. Message: "error processing documents".

**Comment by jlonij** [comment]
Do you have a local instance of the Frame Generator running as a web application? The URL in frame-generator-gui/js/global.js has to be adjusted to connect to your local instance instead of the one we are running at kbresearch. I’ve just changed it to the default local address in the last commit. The size limitation can be customised by editing the check_files() function in the same file.
